name: Windows exe installer build

on:
  push:
    branches: [ main, actions ]
  workflow_dispatch:
    inputs:
      specifiedVersion:
        description: "specified version"
        required: false
      actualVersion:
        description: "numbered version"
        required: false
        default: '1.0.0'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Wix
      uses: i3h/download-release-asset@v1
      with:
        owner: wixtoolset
        repo: wix3
        tag: wix3112rtm
        file: wix311-binaries.zip
    - name: Decompress Wix
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: wix311-binaries.zip
        pathTarget: ./target/wix
    - name: Add Wix to Path
      run: echo "$HOME/target/wix" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B "-Djar.finalName=FNFForwardLauncher" package --file pom.xml
    - name: create version specified
      if: ${{github.event.inputs.specifiedVersion != null}}
      run: java -jar target/FNFForwardLauncher.jar --gitrun ${{github.run_number}} --tagName ${{github.ref}} --specifiedVersion ${{github.event.inputs.specifiedVersion}}
    - name: create version unspecified
      if: ${{github.event.inputs.specifiedVersion == null}}
      run: java -jar target/FNFForwardLauncher.jar --gitrun ${{github.run_number}} --tagName ${{github.ref}}
    - name: Build with Maven again
      run: mvn -B "-Djar.finalName=FNFForwardLauncher" package --file pom.xml
    - name: Make directory
      run: mkdir installer
    - name: Copy file over
      run: copy ./target/FNFForwardLauncher.jar ./installer/
      
    - name: Package to exe
      run: jpackage --input ./installer/ --name FNF-Forward-Launcher --main-jar FNFForwardLauncher.jar --app-version ${{github.event.inputs.actualVersion}} --type exe --icon ./src/main/resources/icon.ico --vendor FNF-Forward --win-dir-chooser --win-shortcut --win-menu --win-menu-group FNF-Forward

    - uses: actions/upload-artifact@v2
      with:
        name: windows exe installer
        path: ./FNF-Forward-Launcher*.exe
